# Generated by Django 5.1.1 on 2024-09-19 15:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Networking', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
