# Generated by Django 5.1.1 on 2024-09-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Networking', '0003_user_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='search_vector',
        ),
    ]
