# Generated by Django 5.1.1 on 2024-09-20 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Networking', '0004_remove_user_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('FRIEND_REQUEST_SENT', 'Friend request sent'), ('FRIEND_REQUEST_ACCEPTED', 'Friend request accepted'), ('FRIEND_REQUEST_REJECTED', 'Friend request rejected'), ('USER_BLOCKED', 'Blocked'), ('USER_UNBLOCKED', 'Unblocked')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
